# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import library_pb2 as library__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in library_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConsultorioServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerarTurno = channel.unary_unary(
                '/consultorio.ConsultorioService/GenerarTurno',
                request_serializer=library__pb2.SolicitudTurno.SerializeToString,
                response_deserializer=library__pb2.Ticket.FromString,
                _registered_method=True)
        self.RegistrarTurnosLote = channel.stream_unary(
                '/consultorio.ConsultorioService/RegistrarTurnosLote',
                request_serializer=library__pb2.SolicitudTurno.SerializeToString,
                response_deserializer=library__pb2.ResumenRegistro.FromString,
                _registered_method=True)
        self.VerPantalla = channel.unary_stream(
                '/consultorio.ConsultorioService/VerPantalla',
                request_serializer=library__pb2.PantallaRequest.SerializeToString,
                response_deserializer=library__pb2.EstadoPantalla.FromString,
                _registered_method=True)
        self.AtencionTiempoReal = channel.stream_stream(
                '/consultorio.ConsultorioService/AtencionTiempoReal',
                request_serializer=library__pb2.EventoEscritorio.SerializeToString,
                response_deserializer=library__pb2.EventoServidor.FromString,
                _registered_method=True)


class ConsultorioServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerarTurno(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegistrarTurnosLote(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerPantalla(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AtencionTiempoReal(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConsultorioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerarTurno': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerarTurno,
                    request_deserializer=library__pb2.SolicitudTurno.FromString,
                    response_serializer=library__pb2.Ticket.SerializeToString,
            ),
            'RegistrarTurnosLote': grpc.stream_unary_rpc_method_handler(
                    servicer.RegistrarTurnosLote,
                    request_deserializer=library__pb2.SolicitudTurno.FromString,
                    response_serializer=library__pb2.ResumenRegistro.SerializeToString,
            ),
            'VerPantalla': grpc.unary_stream_rpc_method_handler(
                    servicer.VerPantalla,
                    request_deserializer=library__pb2.PantallaRequest.FromString,
                    response_serializer=library__pb2.EstadoPantalla.SerializeToString,
            ),
            'AtencionTiempoReal': grpc.stream_stream_rpc_method_handler(
                    servicer.AtencionTiempoReal,
                    request_deserializer=library__pb2.EventoEscritorio.FromString,
                    response_serializer=library__pb2.EventoServidor.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'consultorio.ConsultorioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('consultorio.ConsultorioService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConsultorioService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerarTurno(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/consultorio.ConsultorioService/GenerarTurno',
            library__pb2.SolicitudTurno.SerializeToString,
            library__pb2.Ticket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegistrarTurnosLote(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/consultorio.ConsultorioService/RegistrarTurnosLote',
            library__pb2.SolicitudTurno.SerializeToString,
            library__pb2.ResumenRegistro.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerPantalla(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/consultorio.ConsultorioService/VerPantalla',
            library__pb2.PantallaRequest.SerializeToString,
            library__pb2.EstadoPantalla.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AtencionTiempoReal(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/consultorio.ConsultorioService/AtencionTiempoReal',
            library__pb2.EventoEscritorio.SerializeToString,
            library__pb2.EventoServidor.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
