# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: library.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'library.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlibrary.proto\x12\nbiblioteca\"\x16\n\x08TicketID\x12\n\n\x02id\x18\x01 \x01(\x05\"Y\n\x06Ticket\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07\x63liente\x18\x02 \x01(\t\x12\x10\n\x08problema\x18\x03 \x01(\t\x12\x0e\n\x06idioma\x18\x04 \x01(\t\x12\x10\n\x08\x61tendido\x18\x05 \x01(\x08\"\x07\n\x05Vacio\",\n\x0fResumenRegistro\x12\x19\n\x11total_registrados\x18\x01 \x01(\x05\"9\n\x13SolicitudEscritorio\x12\x12\n\nescritorio\x18\x01 \x01(\t\x12\x0e\n\x06idioma\x18\x02 \x01(\t\"\'\n\x14\x43onfirmacionAtencion\x12\x0f\n\x07mensaje\x18\x01 \x01(\t2\xb2\x02\n\x11\x42ibliotecaService\x12;\n\x0f\x43onsultarTicket\x12\x14.biblioteca.TicketID\x1a\x12.biblioteca.Ticket\x12\x38\n\rListarTickets\x12\x11.biblioteca.Vacio\x1a\x12.biblioteca.Ticket0\x01\x12\x43\n\x0eGenerarTickets\x12\x12.biblioteca.Ticket\x1a\x1b.biblioteca.ResumenRegistro(\x01\x12\x61\n\x18\x41tenderTicketsTiempoReal\x12\x1f.biblioteca.SolicitudEscritorio\x1a .biblioteca.ConfirmacionAtencion(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'library_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TICKETID']._serialized_start=29
  _globals['_TICKETID']._serialized_end=51
  _globals['_TICKET']._serialized_start=53
  _globals['_TICKET']._serialized_end=142
  _globals['_VACIO']._serialized_start=144
  _globals['_VACIO']._serialized_end=151
  _globals['_RESUMENREGISTRO']._serialized_start=153
  _globals['_RESUMENREGISTRO']._serialized_end=197
  _globals['_SOLICITUDESCRITORIO']._serialized_start=199
  _globals['_SOLICITUDESCRITORIO']._serialized_end=256
  _globals['_CONFIRMACIONATENCION']._serialized_start=258
  _globals['_CONFIRMACIONATENCION']._serialized_end=297
  _globals['_BIBLIOTECASERVICE']._serialized_start=300
  _globals['_BIBLIOTECASERVICE']._serialized_end=606
# @@protoc_insertion_point(module_scope)
