# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import library_pb2 as library__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in library_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SoporteTicketsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CrearTicket = channel.unary_unary(
                '/soporte.SoporteTicketsService/CrearTicket',
                request_serializer=library__pb2.SolicitudTicket.SerializeToString,
                response_deserializer=library__pb2.RespuestaTicket.FromString,
                _registered_method=True)
        self.AtenderSiguiente = channel.unary_unary(
                '/soporte.SoporteTicketsService/AtenderSiguiente',
                request_serializer=library__pb2.EscritorioRequest.SerializeToString,
                response_deserializer=library__pb2.TicketAsignado.FromString,
                _registered_method=True)
        self.ConsultarPendientes = channel.unary_unary(
                '/soporte.SoporteTicketsService/ConsultarPendientes',
                request_serializer=library__pb2.Vacio.SerializeToString,
                response_deserializer=library__pb2.ResumenPendientes.FromString,
                _registered_method=True)
        self.ListarPendientes = channel.unary_stream(
                '/soporte.SoporteTicketsService/ListarPendientes',
                request_serializer=library__pb2.Vacio.SerializeToString,
                response_deserializer=library__pb2.Ticket.FromString,
                _registered_method=True)


class SoporteTicketsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CrearTicket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AtenderSiguiente(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarPendientes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarPendientes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SoporteTicketsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CrearTicket': grpc.unary_unary_rpc_method_handler(
                    servicer.CrearTicket,
                    request_deserializer=library__pb2.SolicitudTicket.FromString,
                    response_serializer=library__pb2.RespuestaTicket.SerializeToString,
            ),
            'AtenderSiguiente': grpc.unary_unary_rpc_method_handler(
                    servicer.AtenderSiguiente,
                    request_deserializer=library__pb2.EscritorioRequest.FromString,
                    response_serializer=library__pb2.TicketAsignado.SerializeToString,
            ),
            'ConsultarPendientes': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarPendientes,
                    request_deserializer=library__pb2.Vacio.FromString,
                    response_serializer=library__pb2.ResumenPendientes.SerializeToString,
            ),
            'ListarPendientes': grpc.unary_stream_rpc_method_handler(
                    servicer.ListarPendientes,
                    request_deserializer=library__pb2.Vacio.FromString,
                    response_serializer=library__pb2.Ticket.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'soporte.SoporteTicketsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('soporte.SoporteTicketsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SoporteTicketsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CrearTicket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/soporte.SoporteTicketsService/CrearTicket',
            library__pb2.SolicitudTicket.SerializeToString,
            library__pb2.RespuestaTicket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AtenderSiguiente(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/soporte.SoporteTicketsService/AtenderSiguiente',
            library__pb2.EscritorioRequest.SerializeToString,
            library__pb2.TicketAsignado.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultarPendientes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/soporte.SoporteTicketsService/ConsultarPendientes',
            library__pb2.Vacio.SerializeToString,
            library__pb2.ResumenPendientes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarPendientes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/soporte.SoporteTicketsService/ListarPendientes',
            library__pb2.Vacio.SerializeToString,
            library__pb2.Ticket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
