syntax = "proto3";

package biblioteca;

service BibliotecaService {
  rpc ConsultarTicket(TicketID) returns (Ticket);
  rpc ListarTickets(Vacio) returns (stream Ticket);
  rpc GenerarTickets(stream Ticket) returns (ResumenRegistro);
  rpc AtenderTicketsTiempoReal(stream SolicitudEscritorio) returns (stream ConfirmacionAtencion);
}

message TicketID {
  int32 id = 1;
}

message Ticket {
  int32 id = 1;
  string cliente = 2;
  string problema = 3;
  string idioma = 4;
  bool atendido = 5;
}

message Vacio {}

message ResumenRegistro {
  int32 total_registrados = 1;
}

message SolicitudEscritorio {
  string escritorio = 1;
  string idioma = 2;
}

message ConfirmacionAtencion {
  string mensaje = 1;
}